tfc_organization_name = "your-organization-name"
tfc_project_name = "Your Dify Project"
tfc_workspace_name = "your-dify-on-private-cloud"
tfc_working_directory = "dify-google-cloud-terraform/terraform/environments/dev"
gcp_project_id = "your-dify-project"
