tfc_organization_name = "weseek"
tfc_project_name = "Dify Testbed"
tfc_workspace_name = "dify-testbed-on-cloud-run"
tfc_working_directory = "dify-google-cloud-terraform/terraform/environments/dev"
gcp_project_id = "weseek-dify-testbed"
